# $haproxyConf = <<SCRIPT
# yum update -y
# echo "HAPROXY01" > /proc/sys/kernel/hostname
# yum install gcc pcre-static pcre-devel wget tar haproxy -y
# SCRIPT
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", path: "haproxyconf.sh"
   config.vm.provision "file", source: "/home/github/vagrantfiles/haproxy/haproxy.cfg", destination: "/etc/haproxy/haproxy.cfg"
  # config.ssh.username = "ollemg"

  config.vm.define "haproxy01" do |haproxy01|
    haproxy01.vm.network "public_network", bridge: "wlp7s0"
    haproxy01.vm.network "private_network", ip: "10.255.1.11"
    haproxy01.vm.hostname = "HAPROXY01"
  end
  config.vm.define "haproxy02" do |haproxy02|
    haproxy02.vm.network "public_network", bridge: "wlp7s0"
    haproxy02.vm.network "private_network", ip: "10.255.1.12"
    haproxy02.vm.hostname = "HAPROXY02"
  end
  config.vm.provider "virtualbox" do |vb|
  vb.gui = false
  vb.memory = 512
  vb.cpus = 1
end
end
