Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |v|
     v.memory = 2048
     v.cpus = 1
  end
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "FOG" > /etc/hostname
    yum update -y
    yum install -y wget nmap nano
    cd /opt/
    wget https://github.com/FOGProject/fogproject/archive/1.5.6.tar.gz -O fogproject-1.5.6.tar.gz
    tar -xzvf fogproject-1.5.6.tar.gz
    wget https://github.com/netdata/netdata/releases/download/v1.15.0/netdata-v1.15.0.tar.gz
    tar -xzvf netdata-v1.15.0.tar.gz
  
  SHELL
end
