Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provider "virtualbox"
  config.vm.network "public_network", bridge: "wlp7s0"
  config.vm.provider "virtualbox" do |v|
     v.memory = 2048
     v.cpus = 1
  end
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt update -y
    apt install -y wget nmap nano curl tar mininet xterm
    wget https://www.realvnc.com/download/file/vnc.files/VNC-Server-6.5.0-Linux-x64.deb
    dpkg -i VNC-Server-6.5.0-Linux-x64.deb
    SHELL
  end
